name: Assets

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *" # Run every hour
  workflow_dispatch: # Run manually

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run asset parser
        run: python scripts/assets.py
