name: Assets

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *" # Run every day at 03:00
  workflow_dispatch: # Run manually

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run asset parser
        run: python scripts/assets.py

      - name: Commit and push updated assets.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set Git config with your GitHub login
          git config --global user.email "dejurin@users.noreply.github.com"
          git config --global user.name "dejurin"
          # Add and commit the updated file
          git add public/assets.json
          git commit -m "Update assets.json"
          git push
